# Dependabot configuration for Hugo site
# Documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"

  # Hugo Modules updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "hugo"
      - "dependencies"
    commit-message:
      prefix: "hugo"
      include: "scope"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"

  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: "npm"
      include: "scope"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"

  # Docker updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "docker"
      - "dependencies"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"
