# Dependabot configuration for Hugo site
# Documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"

  # Hugo Modules updates (if you use them)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "hugo"
      - "dependencies"
    commit-message:
      prefix: "hugo"
      prefix-development: "hugo"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"

  # NPM dependencies (if you add any JavaScript packages)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: "npm"
      prefix-development: "npm"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"

  # Docker updates (if you use containers)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "docker"
      - "dependencies"
    commit-message:
      prefix: "docker"
      prefix-development: "docker"
      include: "scope"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"
