# Base Configuration
baseURL: 'https://profincognito.me'  # Updated to custom domain
languageCode: 'en-us'
title: 'Sooraj Sathyanarayanan'
theme: 'hugo-WonderMod'
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'
enableGitInfo: true
enableRobotsTXT: true
enableEmoji: true

# Updated pagination
pagination:
  pagerSize: 10
summaryLength: 70

# Production settings
buildDrafts: false
buildExpired: false
buildFuture: false
watch: false

# Minification Configuration - enabled for production
minify:
  disableXML: true
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false
    css:
      keepCSS2: true
    js:
      keepVars: false

# Primary Parameters
params:
  env: production
  author: "Sooraj Sathyanarayanan"
  description: "Privacy Researcher & Security Strategist | FIDE Arena Grand Master | Chess-Inspired Security Thinking"
  keywords: [Privacy, Security, Chess, Research, FIDE]

  # Site Label
  label:
    text: "Pr0f3ss0r 1nc0gn1t0"
    icon: "/images/favicon/favicon-32x32.png"

  # Repository Info
  githubUsername: "iAnonymous3000"
  githubRepo: "Pr0f3ss0r-1nc0gn1t0"

  # Theme Settings
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowWordCount: true
  ShowBreadCrumbs: true
  ShowToc: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  
  # Social Icons Configuration
  socialIcons:
    - name: "github"
      url: "https://github.com/iAnonymous3000"
      title: "GitHub"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/soorajsathyanarayanan"
      title: "LinkedIn"
    - name: "twitter"
      url: "https://x.com/iAnonymous3000"
      title: "Twitter"
    - name: "mastodon"
      url: "https://mastodon.social/@ianonymous3000"
      title: "Mastodon"
      rel: "me"
    - name: "rss"
      url: "/index.xml"
      title: "RSS"

# Search Configuration
params:
  search:
    enable: true
    type: "client"
    contentLength: 4000
    placeholder: "Search articles and resources..."
    maxResults: 10
    minMatch: 0
    highlightTag: "em"
    noResultsFound: "No results found"
    preload: true
    trigger: "focus"
    resultContentWordCount: 240
    fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.3
      minMatchCharLength: 3
      keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON  # Important for search functionality

  # Asset Configuration for Production
  assets:
    disableFingerprinting: false
    disableHLJS: true
    favicon: "/images/favicon/favicon.ico"
    favicon16x16: "/images/favicon/favicon-16x16.png"
    favicon32x32: "/images/favicon/favicon-32x32.png"
    apple_touch_icon: "/images/favicon/apple-touch-icon.png"
    android_chrome_192: "/images/favicon/android-chrome-192x192.png"
    android_chrome_512: "/images/favicon/android-chrome-512x512.png"
    webmanifest: "/images/favicon/site.webmanifest"
    imageOptimization:
      enable: true
      formats: ["webp", "avif"]
      quality: 85
      stripMetadata: true
      responsiveSizes: [640, 768, 1024, 1366, 1920]
    lazyLoading: true

  # Profile Mode Configuration
  profileMode:
    enabled: true
    title: "Sooraj Sathyanarayanan"
    subtitle: "Privacy Researcher & Security Strategist | FIDE Arena Grand Master | Chess-Inspired Security Thinking"
    imageUrl: "/images/profile/avatar.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Sooraj Sathyanarayanan"
    buttons:
      - name: "Portfolio"
        url: "https://linksta.cc/@ianonymous3000"

  # Privacy Settings
  privacy:
    disqus:
      disable: true
    googleAnalytics:
      anonymizeIP: true
      disable: true
      respectDoNotTrack: true
      useSessionStorage: false
    instagram:
      disable: true
    twitter:
      enableDNT: true
    youtube:
      privacyEnhanced: true

  # Edit Post Configuration
  editPost:
    URL: "https://github.com/iAnonymous3000/Pr0f3ss0r-1nc0gn1t0/blob/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

# Navigation Menu
menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 10
      params:
        feedIcon: true
        feedURL: /blog/index.xml
    - identifier: research
      name: Research
      url: /research/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: chess
      name: Chess
      url: /chess/
      weight: 40
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 50
    - identifier: search
      name: Search
      url: /search/
      weight: 60
    - identifier: about
      name: About
      url: /about/
      weight: 70

# Content Organization
taxonomies:
  tag: tags
  chess_category: chess_categories
  series: series

# Output Settings
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS

# Output Formats
outputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "index"

# Markdown Rendering
markup:
  highlight:
    style: dracula
    lineNos: false
    noClasses: true
    codeFences: true
    guessSyntax: true
    tabWidth: 4
    
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

# Production Build Settings
build:
  writeStats: false
  cacheDir: tmp/hugo_cache

# Server Security Headers for Production
server:
  headers:
    - for: '/**'
      values:
        X-Frame-Options: "SAMEORIGIN"
        X-Content-Type-Options: "nosniff"
        Referrer-Policy: "strict-origin-when-cross-origin"
        Strict-Transport-Security: "max-age=31536000; includeSubDomains"
        Content-Security-Policy: "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
        Permissions-Policy: "camera=(), microphone=(), geolocation=()"
