# Base Configuration
baseURL: 'https://profincognito.me'
languageCode: 'en-us'
title: 'Sooraj Sathyanarayanan'
theme: 'hugo-WonderMod'
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'
enableGitInfo: true
enableRobotsTXT: true
enableEmoji: true

frontmatter:
  lastmod:
    - git
    - fileModTime
    - default

# Pagination
pagination:
  pagerSize: 10
summaryLength: 70

# Production Settings
buildDrafts: false
buildExpired: false
buildFuture: false
watch: false

# Primary Parameters
params:
  env: production
  author: "Sooraj Sathyanarayanan"
  description: "Privacy Researcher & Security Strategist | Advocate for Open Source, Privacy, and Digital Freedom | FIDE Arena Grand Master"
  keywords: [Privacy, Cybersecurity, Open Source, Digital Freedom, Threat Intelligence, Digital Forensics, Privacy Advocacy, Security Research, Chess, Vulnerability Assessment, Penetration Testing, Secure System Design, Data Sovereignty, Anonymity Tools, Incident Response, Threat Modeling, Blockchain Security, Cryptography, Decentralized Systems]

  ShowRssButtonInSectionTermList: true
  
# Site Label
  label:
    text: "Pr0f3ss0r 1nc0gn1t0"
    icon: "/images/favicon/favicon-45x45.png"

  # Repository Info
  githubUsername: "iAnonymous3000"
  githubRepo: "Pr0f3ss0r-1nc0gn1t0"

  # Theme Settings
  defaultTheme: dark
  disableThemeToggle: false
  showReadingTime: true
  showWordCount: true
  showBreadCrumbs: true
  showToc: true
  showPostNavLinks: true
  showCodeCopyButtons: true
  showFullTextInRSS: true
  
  # Social Icons Configuration
  socialIcons:
    - name: "github"
      url: "https://github.com/iAnonymous3000"
      title: "GitHub"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/soorajsathyanarayanan"
      title: "LinkedIn"
    - name: "x" 
      url: "https://x.com/iAnonymous3000"
      title: "X (formerly Twitter)"
    - name: "mastodon"
      url: "https://mastodon.social/@ianonymous3000"
      title: "Mastodon"
      rel: "me"
    - name: "bsky"  
      url: "https://bsky.app/profile/profincognito.me"
      title: "Bluesky"
    - name: "signal"
      url: "https://signal.me/#eu/tao35l1vQxmrWcie6iW3dXlcFo0t3Pzae7WFHEMJnAIqKn2WxP5KnKKq5ClE-ZDD"
      title: "Signal"
    - name: "rss"
      url: "/index.xml"
      title: "RSS Feed"

  # Search Configuration
  search:
    enable: true
    type: "client"
    contentLength: 4000
    placeholder: "Search the archives..."
    maxResults: 10
    minMatch: 0
    highlightTag: "em"
    noResultsFound: "No results found"
    preload: true
    trigger: "focus"
    resultContentWordCount: 240
    fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.3
      minMatchCharLength: 3
      keys: ["title", "permalink", "summary", "content"]
  
  # Privacy Settings
  privacy:
    disqus:
      disable: true
    googleAnalytics:
      anonymizeIP: true
      disable: true
      respectDoNotTrack: true
      useSessionStorage: false
    instagram:
      disable: true
    twitter:
      enableDNT: true
    youtube:
      privacyEnhanced: true

  # Edit Post Configuration
  editPost:
    URL: "https://github.com/iAnonymous3000/Pr0f3ss0r-1nc0gn1t0/blob/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # Profile Mode Configuration
  profileMode:
    enabled: true
    title: "Sooraj Sathyanarayanan"
    subtitle: "Privacy Researcher & Security Strategist | Advocate for Open Source, Privacy, and Digital Freedom | FIDE Arena Grand Master"
    imageUrl: "/images/profile/avatar.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Sooraj Sathyanarayanan"
    buttons:
      - name: "Portfolio"
        url: "https://linksta.cc/@ianonymous3000"
        rel: "me noopener"
      - name: "VERIFIED WITH KEYOXIDE ✓"
        url: "https://keyoxide.org/aspe:keyoxide.org:3VP5CIVZ6MQ767ELCSBRCPSV4M"
        rel: "me noopener"

# Navigation Menu
menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 10
      params:
        feedIcon: true
        feedURL: /blog/index.xml
    - identifier: research
      name: Research
      url: /research/
      weight: 20
      params:
        feedIcon: true
        feedURL: /research/index.xml    
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
      params:
        feedIcon: true
        feedURL: /projects/index.xml    
    - identifier: chess
      name: Chess
      url: /chess/
      weight: 40
      params:
        feedIcon: true
        feedURL: /chess/index.xml    
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 50    
    - identifier: search
      name: Search
      url: /search/
      weight: 60    
    - identifier: about
      name: About
      url: /about/
      weight: 70
    - identifier: support
      name: Support
      url: /support/
      weight: 80

# Content Organization
taxonomies:
  tag: tags
  series: series

# Output Settings
outputs:
  home:
    - HTML
    - RSS
    - JSON  # Important for search functionality
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS

# Output Formats
outputFormats:
  RSS:
    mediaType: "application/rss+xml"
    baseName: "index"

# Markdown Rendering
markup:
  highlight:
    style: dracula
    lineNos: false
    noClasses: true
    codeFences: true
    guessSyntax: true
    tabWidth: 4
    
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

# Production Build Settings
build:
  writeStats: false
  cacheDir: tmp/hugo_cache

# Asset Configuration for Production
assets:
  disableFingerprinting: false
  disableHLJS: true
  favicon: "/images/favicon/favicon.ico"
  favicon16x16: "/images/favicon/favicon-16x16.png"
  favicon32x32: "/images/favicon/favicon-32x32.png"
  appleTouchIcon: "/images/favicon/apple-touch-icon.png"
  androidChrome192: "/images/favicon/android-chrome-192x192.png"
  androidChrome512: "/images/favicon/android-chrome-512x512.png"
  webmanifest: "/images/favicon/site.webmanifest"
  imageOptimization:
    enable: true
    formats: ["webp", "avif"]
    quality: 85
    stripMetadata: true
    responsiveSizes: [640, 768, 1024, 1366, 1920]
  lazyLoading: true
