name: Onion Mirror

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'content/**'
      - 'config.yaml'
      - '.github/workflows/onion-mirror.yml'

jobs:
  setup-onion:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tor nginx
          sudo systemctl stop tor || true
          sudo systemctl stop nginx || true

      - name: Setup Tor Hidden Service
        run: |
          # First ensure tor user exists
          if ! id -u debian-tor > /dev/null 2>&1; then
            sudo adduser --system --group --no-create-home debian-tor
          fi
          
          # Create base directory with correct permissions
          sudo mkdir -p /var/lib/tor
          sudo chown -R debian-tor:debian-tor /var/lib/tor
          sudo chmod 700 /var/lib/tor
          
          # Setup hidden service directory
          sudo -u debian-tor mkdir -p /var/lib/tor/hidden_service
          sudo -u debian-tor chmod 700 /var/lib/tor/hidden_service
          
          # Restore private key with correct ownership
          echo "${{ secrets.TOR_PRIVATE_KEY }}" | base64 -d | sudo -u debian-tor tee /var/lib/tor/hidden_service/hs_ed25519_secret_key > /dev/null
          sudo -u debian-tor chmod 600 /var/lib/tor/hidden_service/hs_ed25519_secret_key
          
          # Debug: Show permissions (sanitized output)
          ls -ld /var/lib/tor
          ls -ld /var/lib/tor/hidden_service

      - name: Configure Tor
        run: |
          sudo tee /etc/tor/torrc << 'EOF'
          DataDirectory /var/lib/tor
          HiddenServiceDir /var/lib/tor/hidden_service/
          HiddenServicePort 80 127.0.0.1:80
          HiddenServiceVersion 3
          Log notice stdout
          EOF
          
          sudo chown -R debian-tor:debian-tor /etc/tor
          sudo chmod 644 /etc/tor/torrc

      - name: Configure Nginx
        run: |
          sudo tee /etc/nginx/conf.d/onion_mirror.conf << 'EOF'
          server {
              listen 127.0.0.1:80;
              server_name _;
              
              location / {
                  proxy_pass https://profincognito.me;
                  proxy_set_header Host profincognito.me;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
          EOF
          
          sudo nginx -t

      - name: Start Services
        run: |
          # Start Tor with proper user
          sudo -u debian-tor tor -f /etc/tor/torrc &
          TOR_PID=$!
          
          echo "Waiting for Tor to initialize..."
          sleep 30
          
          if ! ps -p $TOR_PID > /dev/null; then
            echo "Tor failed to start. Checking logs..."
            sudo tail -n 50 /var/log/tor/log || true
            exit 1
          fi
          
          # Start Nginx
          sudo nginx
          
          # Verify services
          ps aux | grep -v grep | grep tor
          ps aux | grep -v grep | grep nginx

      - name: Verify Onion Service
        run: |
          if [ -f /var/lib/tor/hidden_service/hostname ]; then
            CURRENT_ONION=$(sudo -u debian-tor cat /var/lib/tor/hidden_service/hostname | tr -d '\n\r')
            echo "Found onion address: ${CURRENT_ONION}"
            
            if [ "$CURRENT_ONION" != "${{ secrets.TOR_ADDRESS }}" ]; then
              echo "Error: Onion address mismatch!"
              exit 1
            fi
            echo "✓ Onion service verified"
          else
            echo "Error: Hostname file not found"
            sudo -u debian-tor ls -la /var/lib/tor/hidden_service/
            exit 1
          fi

      - name: Update Hugo Config
        if: success()
        run: |
          sudo apt-get install -y python3-pip
          pip3 install yq
          
          yq eval -i '
            .params.mirrors = (
              .params.mirrors // [] | map(select(.name != "Onion Mirror"))
            ) + [{
              "name": "Onion Mirror",
              "url": strenv(ONION_URL),
              "icon": "tor",
              "info": "Access via Tor Browser"
            }]
          ' config.yaml
        env:
          ONION_URL: "http://${{ secrets.TOR_ADDRESS }}"

      - name: Commit Changes
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if git diff --exit-code config.yaml; then
            echo "No changes to commit"
          else
            git add config.yaml
            git commit -m "Update Onion mirror address [skip ci]"
            git push
          fi
