name: Onion Mirror

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'content/**'
      - 'config.yaml'
      - '.github/workflows/onion-mirror.yml'

jobs:
  setup-onion:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y tor nginx

      - name: Setup Tor Hidden Service
        run: |
          sudo rm -rf /var/lib/tor/hidden_service
          sudo mkdir -p /var/lib/tor/hidden_service
          sudo chmod 700 /var/lib/tor/hidden_service
          sudo chown debian-tor:debian-tor /var/lib/tor/hidden_service

          # Restore private key from GitHub secret
          echo "${{ secrets.TOR_PRIVATE_KEY }}" | base64 -d | sudo tee /var/lib/tor/hidden_service/hs_ed25519_secret_key > /dev/null
          sudo chmod 600 /var/lib/tor/hidden_service/hs_ed25519_secret_key
          sudo chown debian-tor:debian-tor /var/lib/tor/hidden_service/hs_ed25519_secret_key

      - name: Configure Tor
        run: |
          sudo tee /etc/tor/torrc > /dev/null << 'EOF'
          HiddenServiceDir /var/lib/tor/hidden_service/
          HiddenServicePort 80 127.0.0.1:80
          HiddenServiceVersion 3
EOF

      - name: Configure Nginx
        run: |
          sudo tee /etc/nginx/conf.d/onion_mirror.conf << 'EOF'
          server {
              listen 127.0.0.1:80;
              server_name _;
              
              # Security Headers
              server_tokens off;
              add_header X-Content-Type-Options nosniff;
              add_header X-Frame-Options DENY;
              add_header X-XSS-Protection "1; mode=block";
              
              location / {
                  proxy_pass https://profincognito.me;
                  proxy_set_header Host profincognito.me;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
EOF
          sudo nginx -t

      - name: Start Services
        run: |
          sudo systemctl start tor
          sudo systemctl start nginx
          sleep 10  # Give services time to start

          # Verify services are running
          if ! systemctl is-active --quiet tor; then
            echo "Error: Tor failed to start"
            sudo journalctl -u tor --no-pager
            exit 1
          fi

          if ! systemctl is-active --quiet nginx; then
            echo "Error: Nginx failed to start"
            sudo journalctl -u nginx --no-pager
            exit 1
          fi

      - name: Verify and Update Config
        run: |
          # Install yq
          sudo apt-get install -y python3-pip
          pip3 install yq
          
          # Wait for hidden service to be ready
          sleep 30
          
          if [ -f /var/lib/tor/hidden_service/hostname ]; then
            CURRENT_ONION=$(sudo cat /var/lib/tor/hidden_service/hostname)
            if [ "$CURRENT_ONION" != "${{ secrets.TOR_ADDRESS }}" ]; then
              echo "Error: Onion address mismatch!"
              echo "Expected: ${{ secrets.TOR_ADDRESS }}"
              echo "Got: $CURRENT_ONION"
              exit 1
            fi
            
            # Update Hugo config
            yq eval -i ".params.mirrors = (.params.mirrors // []) + [{\"name\": \"Onion Mirror\", \"url\": \"http://$CURRENT_ONION\", \"icon\": \"tor\", \"info\": \"Access via Tor Browser\"}]" config.yaml
            echo "✓ Onion service verified and config updated"
          else
            echo "Error: Onion hostname file not found"
            sudo ls -la /var/lib/tor/hidden_service/
            exit 1
          fi

      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add config.yaml
          git diff-index --quiet HEAD || (git commit -m "Update Onion mirror address [skip ci]" && git push)
