name: Onion Mirror

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'content/**'
      - 'config.yaml'
      - '.github/workflows/onion-mirror.yml'

jobs:
  setup-onion:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tor nginx
          sudo systemctl stop tor || true
          sudo systemctl stop nginx || true

      - name: Verify System Configuration
        run: |
          if ! id -u debian-tor > /dev/null 2>&1; then
            sudo adduser --system --group --no-create-home debian-tor
          fi
          tor --version
          which tor

      - name: Setup Tor Hidden Service
        shell: bash
        env:
          TOR_PRIVATE_KEY: ${{ secrets.TOR_PRIVATE_KEY }}
        run: |
          # Clean existing directories
          sudo rm -rf /var/lib/tor/hidden_service || true
          sudo rm -rf /var/lib/tor || true
          
          # Create base directory with proper permissions
          sudo install -d -m 700 -o debian-tor -g debian-tor /var/lib/tor
          
          # Create hidden service directory with proper permissions
          sudo -u debian-tor install -d -m 700 /var/lib/tor/hidden_service
          
          # Write private key if provided
          if [ -n "$TOR_PRIVATE_KEY" ]; then
            echo "$TOR_PRIVATE_KEY" | base64 -d | sudo -u debian-tor tee /var/lib/tor/hidden_service/hs_ed25519_secret_key > /dev/null
            if [ $? -ne 0 ]; then
              echo "Failed to write private key"
              exit 1
            fi
            sudo -u debian-tor chmod 600 /var/lib/tor/hidden_service/hs_ed25519_secret_key
          else
            echo "TOR_PRIVATE_KEY is not set"
            exit 1
          fi
          
          # Verify permissions
          echo "Directory permissions:"
          sudo ls -la /var/lib/tor
          sudo -u debian-tor ls -la /var/lib/tor/hidden_service

      - name: Configure Tor
        run: |
          sudo tee /etc/tor/torrc << 'EOF'
          DataDirectory /var/lib/tor
          HiddenServiceDir /var/lib/tor/hidden_service/
          HiddenServicePort 80 127.0.0.1:8080
          HiddenServiceVersion 3
          Log notice stdout
          EOF
          
          sudo chown -R debian-tor:debian-tor /etc/tor
          sudo chmod 644 /etc/tor/torrc

      - name: Configure and Start Nginx
        run: |
          sudo tee /etc/nginx/conf.d/onion_mirror.conf << 'EOF'
          server {
              listen 127.0.0.1:8080;
              server_name _;
              
              location / {
                  proxy_pass https://profincognito.me;
                  proxy_set_header Host profincognito.me;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_ssl_server_name on;
                  proxy_connect_timeout 60s;
                  proxy_read_timeout 60s;
              }
              
              access_log /var/log/nginx/access.tor.log;
              error_log /var/log/nginx/error.tor.log;
          }
          EOF
          
          sudo nginx -t
          sudo nginx

      - name: Start Tor
        run: |
          sudo -u debian-tor tor -f /etc/tor/torrc &
          echo "Waiting for Tor to initialize (60 seconds)..."
          sleep 60
          
          if ! pgrep -x tor > /dev/null; then
            echo "Tor failed to start"
            sudo cat /var/log/tor/log || true
            exit 1
          fi

      - name: Verify Onion Service
        env:
          EXPECTED_ONION: ${{ secrets.TOR_ADDRESS }}
        run: |
          ATTEMPTS=0
          MAX_ATTEMPTS=10
          
          while [ ! -f /var/lib/tor/hidden_service/hostname ] && [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
            echo "Waiting for hostname file... (attempt $((ATTEMPTS + 1))/$MAX_ATTEMPTS)"
            sleep 30
            ATTEMPTS=$((ATTEMPTS + 1))
          done

          if [ -f /var/lib/tor/hidden_service/hostname ]; then
            CURRENT_ONION=$(sudo -u debian-tor cat /var/lib/tor/hidden_service/hostname | tr -d '\n\r')
            echo "Found onion address: ${CURRENT_ONION}"
            
            if [ "$CURRENT_ONION" = "$EXPECTED_ONION" ]; then
              echo "✓ Onion service verified"
              curl --socks5-hostname 127.0.0.1:9050 -v "http://${CURRENT_ONION}.onion" || true
            else
              echo "Error: Onion address mismatch!"
              echo "Expected: $EXPECTED_ONION"
              echo "Got: $CURRENT_ONION"
              exit 1
            fi
          else
            echo "Error: Hostname file not found after $MAX_ATTEMPTS attempts"
            sudo -u debian-tor ls -la /var/lib/tor/hidden_service/
            exit 1
          fi

      - name: Update Hugo Config
        if: success()
        env:
          ONION_URL: ${{ secrets.TOR_ADDRESS }}
        run: |
          sudo apt-get install -y python3-pip
          pip3 install yq
          
          yq eval -i '
            .params.mirrors = (
              .params.mirrors // [] | map(select(.name != "Onion Mirror"))
            ) + [{
              "name": "Onion Mirror",
              "url": strenv(ONION_URL),
              "icon": "tor",
              "info": "Access via Tor Browser"
            }]
          ' config.yaml

      - name: Commit Changes
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if git diff --exit-code config.yaml; then
            echo "No changes to commit"
          else
            git add config.yaml
            git commit -m "Update Onion mirror address [skip ci]"
            git push
          fi
