name: Update Theme

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering via GitHub Actions UI

jobs:
  update-theme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fetch the latest theme version
      - name: Clone the latest WonderMod theme
        run: |
          echo "Cloning the latest WonderMod theme..."
          git clone --depth 1 https://github.com/Wonderfall/hugo-WonderMod.git /tmp/hugo-WonderMod
          echo "Replacing the current theme with the updated version..."
          rm -rf themes/hugo-WonderMod
          mv /tmp/hugo-WonderMod themes/hugo-WonderMod

      # Step 3: Commit and push changes
      - name: Commit and push changes
        run: |
          echo "Committing changes..."
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add themes/hugo-WonderMod
          git commit -m "Automated update of WonderMod theme" || echo "No changes to commit"
          git push origin main
